languages:
   PHP: true
exclude_paths:
- "vendor/*"
- "public/*"
- "app/*"
- "storage/*"
- "node_modules/*"
- "tests/mock/*"
- "config/*"
- "database/migrations/*"
- "database/seeds/*"

ratings:
   paths:
   - app/**

engines:
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false